### ISSUE TITLE
No virtual keycode for question mark on linux

### ISSUE THREAD

**Issue by stevebob** [rust-windowing/glutin#1104] opened 2019-02-26 07:24 UTC
I've only tested this on linux. Pressing shift+'/' ('?') produces:
```
KeyboardInput {
    device_id: DeviceId(
        X(
            DeviceId(
                3
            )
        )
    ),
    input: KeyboardInput {
        scancode: 26,
        state: Pressed,
        virtual_keycode: None,
        modifiers: ModifiersState {
            shift: true,
            ctrl: false,
            alt: false,
            logo: false
        }
    }
}
```
Without the shift key pressed, it detects the slash just fine.

**Comment by ZeGentzy** [comment] 2019-02-27 00:21
Can't reproduce: 
```
DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
WindowEvent { window_id: WindowId(X(WindowId(73400323))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 53, state: Pressed, virtual_keycode: Some(Slash), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
WindowEvent { window_id: WindowId(X(WindowId(73400323))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 53, state: Pressed, virtual_keycode: None, modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
WindowEvent { window_id: WindowId(X(WindowId(73400323))), event: ReceivedCharacter('?') }
DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 53, state: Released, virtual_keycode: Some(Slash), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
WindowEvent { window_id: WindowId(X(WindowId(73400323))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 53, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
DeviceEvent { device_id: DeviceId(X(DeviceId(12))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
WindowEvent { window_id: WindowId(X(WindowId(73400323))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
```

Can we get some system info, and keyboard layout?

**Comment by ZeGentzy** [comment] 2019-03-15 22:54
I forgot to mention this, but even if I could reproduce it, it would be an upstream issue from winit.

**Comment by stevebob** [comment] 2019-03-16 15:50
My output was from running on linux, with the dvorak keyboard layout.

@ZeGentzy looking at the output you pasted, it looks like you're reproducing the problem. Here's a line from your output corresponding to pressing shift + "?/" (ie. question mark), with newlines added for clarity
```
WindowEvent {
  window_id: WindowId(X(WindowId(73400323))),
  event: KeyboardInput {
    device_id: DeviceId(X(DeviceId(3))), 
    input: KeyboardInput { 
      scancode: 53,
      state: Pressed, 
      virtual_keycode: None,   // <-- this is the problem
      modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
```
When you pressed the "?/" key, the virtual_keycode is None. Looking at the definition of the `VirtualKeyCode` type[1], I can't see a variant corresponding to the question mark.

Also you're right, this is an issue with winit, not glutin. Should I close this and make an issue there or is there enough overlap?
1. https://docs.rs/winit/0.19.0/winit/enum.VirtualKeyCode.html

**Comment by ZeGentzy** [comment] 2019-03-16 18:45
Ah, I did not spot that. File it upstream and post a link to the new issue right here.

**Comment by stevebob** [comment] 2019-03-16 20:17
https://github.com/tomaka/winit/issues/812

**Comment by ZeGentzy** [comment] 2019-05-20 07:39
Closing in favor of upstream. rust-windowing/winit#812

**Closed by ZeGentzy** 2019-05-20 07:39 UTC
Labels: platform: Wayland, platform: X11, status: upstream, status: waiting, type: bug
