### ISSUE TITLE
Problem compiling on Android

### ISSUE THREAD

**Issue by toastmod** [rust-windowing/glutin#1361] opened 2021-06-27 04:15 UTC
Hey there I'm trying to compile the glium triangle on cargo apk, this error pops up when glutin tries to compile.

```
   Compiling glutin v0.27.0
error[E0599]: no method named `set_suspend_callback` found for reference `&EventLoopWindowTarget<T>` in the current scope
  --> C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.27.0\src\api\android\mod.rs:76:12
   |
76 |         el.set_suspend_callback(Some(Box::new(move |suspended| {
   |            ^^^^^^^^^^^^^^^^^^^^ method not found in `&EventLoopWindowTarget<T>`

error[E0615]: attempted to take value of method `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.27.0\src\api\egl\mod.rs:621:17
    |
621 |         if !egl.SwapBuffersWithDamageKHR.is_loaded() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
621 |         if !egl.SwapBuffersWithDamageKHR(_, _, _, _).is_loaded() {
    |                                         ^^^^^^^^^^^^

error[E0615]: attempted to take value of method `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\glutin-0.27.0\src\api\egl\mod.rs:664:13
    |
664 |         egl.SwapBuffersWithDamageKHR.is_loaded()
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
664 |         egl.SwapBuffersWithDamageKHR(_, _, _, _).is_loaded()
    |                                     ^^^^^^^^^^^^

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0599, E0615.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `glutin`

To learn more, run the command again with --verbose.
Error: Command `cargo build --target aarch64-linux-android` had a non-zero exit code.

```

**Comment by toastmod** [comment] 2021-06-27 04:35
After commenting out the entire functionality of `SwapBuffersWithDamage` I now get this:
```
C:/Users/anumr/.cargo/bin/cargo.exe apk run
   Compiling testemptyapp v0.1.0 (C:\Users\anumr\Documents\devel\testemptyapp)
error: linking with `C:\Users\anumr\AppData\Local\Android\SDK\ndk\22.1.7171670\toolchains\llvm\prebuilt\windows-x86_64\bin\aarch64-linux-android29-clang.cmd` failed: exit code: 1
  |
  = note: "C:\\Users\\anumr\\AppData\\Local\\Android\\SDK\\ndk\\22.1.7171670\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android29-clang.cmd" "-Wl,--allow-multiple-definition" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.0.rcgu.o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.1.rcgu.o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.2.rcgu.o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.3.rcgu.o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.4.rcgu.o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.testemptyapp.6drpd5ij-cgu.5.rcgu.o" "-o" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\testemptyapp-12d97f791fcb82fc.7xskpr6v0cg63bj.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps" "-L" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\debug\\deps" "-L" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib" "-Wl,-Bstatic" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libtestemptyapp.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libglium-9682f6b4b476cc12.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libbacktrace-93da5820d7031afc.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libminiz_oxide-f1a6b1e0a8062022.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libadler-717a31b5cb46ba2e.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libobject-4f0c50d26829c4d8.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libmemchr-c5cd3d2f53c8f5bd.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libaddr2line-ad24f1ad80c7753f.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libgimli-17a3119c0cb78b72.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\librustc_demangle-e2a339c8c8513198.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libmemoffset-c92af714f57a2f15.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libtakeable_option-2e6e1e88f0ce3477.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libglutin-68ffce9ce1dd6f34.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libandroid_glue-e4f9a9fcd9664fe9.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libparking_lot-f988ffe9469bea3a.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libparking_lot_core-59d13c0867fa5122.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libsmallvec-c09ffa90d9fd3c8c.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\liblock_api-c6749ed98291bf2f.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libscopeguard-f82217dd0ab5b36c.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libwinit-01e6551df56b44e1.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libraw_window_handle-d4affac43120794f.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libndk_glue-506274ed68be7554.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\liblibc-ec28166fed277584.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libndk-9e0ca6e09c5beea4.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libjni_sys-96654152f2c504cc.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libndk_sys-4f7c740d8596b9a2.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libthiserror-f846ebb03030b666.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libnum_enum-6441f48a0ded5d0d.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libinstant-ec4db9cc3d9428dd.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libbitflags-10d4a249843b226a.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\liblog-346feec9abb3f47e.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libcfg_if-981fd96707ddb754.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libglutin_egl_sys-3074fc715ce2e9af.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\libfnv-4e2b8ae8984965c4.rlib" "C:\\Users\\anumr\\Documents\\devel\\testemptyapp\\target\\aarch64-linux-android\\debug\\deps\\liblazy_static-3106a1cd1a24d58d.rlib" "-Wl,--start-group" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libstd-3a3c67c83f6e9693.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libpanic_unwind-4a7f1b4e8df66edf.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libminiz_oxide-1c444b92bf260b59.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libadler-a34baa6bd1fa056a.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libobject-9990946deb29ccd8.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libaddr2line-eac9d989053b21b1.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libgimli-76b6de8634d853f5.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libstd_detect-2ba4973c38d1e35a.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_demangle-1b7f8c5062d787de.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libhashbrown-7c08916365b94a34.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_std_workspace_alloc-085a7d01870b7259.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libunwind-3c84bbb091cf0b9c.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcfg_if-442d7bfd08c535f4.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\liblibc-531b225150a26641.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\liballoc-421c1f5001becd46.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\librustc_std_workspace_core-b8bb8ba11acf6a13.rlib" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcore-8397e2343cbd11b1.rlib" "-Wl,--end-group" "C:\\Users\\anumr\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\aarch64-linux-android\\lib\\libcompiler_builtins-5ccae58f29f153e7.rlib" "-Wl,-Bdynamic" "-landroid" "-ldl" "-llog" "-lgcc" "-lc" "-lm"
  = note: ld: error: undefined symbol: cargo_apk_injected_glue_get_native_window
          >>> referenced by lib.rs:123 (C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\android_glue-0.2.3\src\lib.rs:123)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.15.rcgu.o:(android_glue::get_native_window::h5b4a661439ed68f3) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: cargo_apk_injected_glue_add_sync_event_handler
          >>> referenced by lib.rs:86 (C:\Users\anumr\.cargo\registry\src\github.com-1ecc6299db9ec823\android_glue-0.2.3\src\lib.rs:86)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.15.rcgu.o:(android_glue::add_sync_event_handler::h186bef973cc3fe43) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglGetDisplay
          >>> referenced by egl_bindings.rs:466 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:466)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::GetDisplay::h0440b407e9144643) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglQueryString
          >>> referenced by egl_bindings.rs:536 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:536)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::QueryString::h93904ce483e7d142) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglSwapBuffers
          >>> referenced by egl_bindings.rs:571 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:571)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::SwapBuffers::h4eef9bf53a151af1) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglChooseConfig
          >>> referenced by egl_bindings.rs:305 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:305)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::ChooseConfig::hf00c4b3b0304ccec) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglGetConfigAttrib
          >>> referenced by egl_bindings.rs:431 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:431)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::GetConfigAttrib::hb92f220567e0cff2) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          
          ld: error: undefined symbol: eglGetCurrentContext
          >>> referenced by egl_bindings.rs:445 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:445)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::GetCurrentContext::hab74422a97401598) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          >>> referenced by egl_bindings.rs:445 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:445)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::GetCurrentContext::h2bf3969052045e9e) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglGetError
          >>> referenced by egl_bindings.rs:473 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:473)
          >>>               testemptyapp.testemptyapp.cdyc5wuw-cgu.7.rcgu.o:(glutin_egl_sys::egl::Egl::GetError::ha08488adbd8e8442) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libtestemptyapp.rlib
          >>> referenced by egl_bindings.rs:473 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:473)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::GetError::h77dceed31a6c1054) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglInitialize
          >>> referenced by egl_bindings.rs:508 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:508)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::Initialize::h78bb50a25b10e91c) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglMakeCurrent
          >>> referenced by egl_bindings.rs:515 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:515)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::MakeCurrent::ha5cc51e1f63c2d78) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglSwapInterval
          >>> referenced by egl_bindings.rs:585 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:585)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::SwapInterval::h6e812f69c3b380ef) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglCreateContext
          >>> referenced by egl_bindings.rs:326 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:326)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::CreateContext::h52ce05e3ec1be95e) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglDestroyContext
          >>> referenced by egl_bindings.rs:403 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:403)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::DestroyContext::h1a0cc217a43a6fbc) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglDestroySurface
          >>> referenced by egl_bindings.rs:417 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:417)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::DestroySurface::hfb163e9e66193c92) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglGetProcAddress
          >>> referenced by egl_bindings.rs:494 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:494)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::GetProcAddress::h14329ad67c02776c) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglGetCurrentDisplay
          >>> referenced by egl_bindings.rs:452 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:452)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::GetCurrentDisplay::hf7cafdb6387a7b15) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglGetCurrentSurface
          >>> referenced by egl_bindings.rs:459 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:459)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::GetCurrentSurface::hd3da0c59ee7e0e94) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglCreateWindowSurface
          >>> referenced by egl_bindings.rs:396 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:396)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::CreateWindowSurface::h4cec84d9beeb766a) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          
          ld: error: undefined symbol: eglBindAPI
          >>> referenced by egl_bindings.rs:291 (C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\build\glutin_egl_sys-f252a55e216a3ce8\out\egl_bindings.rs:291)
          >>>               glutin-68ffce9ce1dd6f34.glutin.3hocyxhp-cgu.15.rcgu.o:(glutin_egl_sys::egl::Egl::BindAPI::h227f93171c3a7284) in archive C:\Users\anumr\Documents\devel\testemptyapp\target\aarch64-linux-android\debug\deps\libglutin-68ffce9ce1dd6f34.rlib
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: could not compile `testemptyapp`

To learn more, run the command again with --verbose.
Error: Command `cargo build --target aarch64-linux-android` had a non-zero exit code.

Process finished with exit code 1
```

**Comment by PureTryOut** [comment] 2021-09-08 13:37
I can reproduce this issue, although I'm currently building for i686 but I doubt that matters much.

**Comment by PureTryOut** [comment] 2021-09-08 13:39
Oh this seems to be a duplicate of #1307

**Comment by lattice0** [comment] 2022-05-19 02:09
same https://github.com/rust-windowing/glutin/issues/1405

**Comment by MarijnS95** [comment] 2022-05-26 13:59
Going to close this as a duplicate of https://github.com/rust-windowing/glutin/issues/1307, so that we only have one tracking issue!

**Closed by MarijnS95** 2022-05-26 13:59 UTC
Labels: platform: Android, status: needs investigation

**Comment by MarijnS95** [comment] 2022-05-26 14:00
Duplicate of #1307

(Let's see if GH picks it up this way)
