### ISSUE TITLE
Proprietary Nvidia (Wayland): eglCreateWindowSurface failed

### ISSUE THREAD

**Issue by aidanharris** [rust-windowing/glutin#1188] opened 2019-07-14 12:12 UTC
Migrated from [jwilm/alacritty#1269](https://github.com/jwilm/alacritty/issues/1269)

A segfault occurs when using glutin with the binary Nvidia driver and a Wayland compositor.

Backtrace obtained from `rust-gdb` from running glutin's window example:

https://gist.github.com/aidanharris/f1fe409c463e79c575242a9edd255ea8

If I force the mesa driver to be used instead of Nvidia's library (`env LD_PRELOAD=/usr/lib64/libEGL.so cargo run --example window`) no segfault occurs and the example runs fine (I assume mesa is doing software rendering but it does work so perhaps this is an issue with the Nvidia driver?).

**Comment by kchibisov** [comment] 2019-07-14 14:43
@aidanharris Which `wayland` compositor are you running?

**Comment by aidanharris** [comment] 2019-07-14 14:47
@kchibisov GNOME (mutter) but I'm not sure it matters. The issue also occurs with KDE's Kwin.

**Comment by kchibisov** [comment] 2019-07-14 14:50
@aidanharris Some wayland compositors don't work with nvidia binary driver, so was ensuring that your compositor supports it.

**Comment by ZeGentzy** [comment] 2019-07-14 21:18
Can you do the following `export LD_PRELOAD=/usr/lib64/libEGL.so ; glxinfo && eglinfo && glinfo`?

**Comment by aidanharris** [comment] 2019-07-14 21:44
`glxinfo` fails as follows:

```
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig
```

(this is actually expected because XWayland currently doesn't work properly with Nvidia's driver so any X11 applications using glx won't work at all but egl should work with Wayland applications that don't use X11)

<details>
  <summary>eglinfo</summary>

```
EGL client extensions string:
    EGL_EXT_client_extensions EGL_EXT_device_base
    EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base
    EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug
    EGL_EXT_platform_wayland EGL_EXT_platform_x11 EGL_MESA_platform_gbm
    EGL_MESA_platform_surfaceless EGL_EXT_platform_device

GBM platform:
eglinfo: eglInitialize failed

Wayland platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_KHR_cl_event2 EGL_KHR_config_attribs
    EGL_KHR_context_flush_control EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_query_driver
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8  0  0  0 0 0x00--         y  y  y     win
0x02 32  0  8  8  8  8 16  0  0 0 0x00--         y  y  y     win
0x03 32  0  8  8  8  8 24  0  0 0 0x00--         y  y  y     win
0x04 32  0  8  8  8  8 24  8  0 0 0x00--         y  y  y     win
0x05 32  0  8  8  8  8 32  0  0 0 0x00--         y  y  y     win
0x06 24  0  8  8  8  0  0  0  0 0 0x00--         y  y  y     win
0x07 24  0  8  8  8  0 16  0  0 0 0x00--         y  y  y     win
0x08 24  0  8  8  8  0 24  0  0 0 0x00--         y  y  y     win
0x09 24  0  8  8  8  0 24  8  0 0 0x00--         y  y  y     win
0x0a 24  0  8  8  8  0 32  0  0 0 0x00--         y  y  y     win

X11 platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_KHR_cl_event2 EGL_KHR_config_attribs
    EGL_KHR_context_flush_control EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image_base EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_query_driver
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8  0  0  0 0 0x23TC      a  y  y  y     win,pb,pix
0x02 32  0  8  8  8  8 16  0  0 0 0x23TC      a  y  y  y     win,pb,pix
0x03 32  0  8  8  8  8 24  0  0 0 0x23TC      a  y  y  y     win,pb,pix
0x04 32  0  8  8  8  8 24  8  0 0 0x23TC      a  y  y  y     win,pb,pix
0x05 32  0  8  8  8  8 32  0  0 0 0x23TC      a  y  y  y     win,pb,pix
0x06 24  0  8  8  8  0  0  0  0 0 0x23TC      y  y  y  y     win,pb,pix
0x07 24  0  8  8  8  0 16  0  0 0 0x23TC      y  y  y  y     win,pb,pix
0x08 24  0  8  8  8  0 24  0  0 0 0x23TC      y  y  y  y     win,pb,pix
0x09 24  0  8  8  8  0 24  8  0 0 0x23TC      y  y  y  y     win,pb,pix
0x0a 24  0  8  8  8  0 32  0  0 0 0x23TC      y  y  y  y     win,pb,pix
0x0b 32  0  8  8  8  8  0  0  0 0 0x24DC      a  y  y  y     win,pb,pix
0x0c 32  0  8  8  8  8 16  0  0 0 0x24DC      a  y  y  y     win,pb,pix
0x0d 32  0  8  8  8  8 24  0  0 0 0x24DC      a  y  y  y     win,pb,pix
0x0e 32  0  8  8  8  8 24  8  0 0 0x24DC      a  y  y  y     win,pb,pix
0x0f 32  0  8  8  8  8 32  0  0 0 0x24DC      a  y  y  y     win,pb,pix
0x10 24  0  8  8  8  0  0  0  0 0 0x24DC      y  y  y  y     win,pb,pix
0x11 24  0  8  8  8  0 16  0  0 0 0x24DC      y  y  y  y     win,pb,pix
0x12 24  0  8  8  8  0 24  0  0 0 0x24DC      y  y  y  y     win,pb,pix
0x13 24  0  8  8  8  0 24  8  0 0 0x24DC      y  y  y  y     win,pb,pix
0x14 24  0  8  8  8  0 32  0  0 0 0x24DC      y  y  y  y     win,pb,pix
0x15 16  0  5  6  5  0  0  0  0 0 0x00--      y  y  y  y     pb

Device platform:
eglinfo: eglInitialize failed
```

</details>

For comparison here's `eglinfo` without the `LD_PRELOAD`:

<details>
  <summary>eglinfo</summary>

```
EGL client extensions string:
    EGL_EXT_platform_base EGL_EXT_device_base
    EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions
    EGL_KHR_debug EGL_KHR_platform_x11 EGL_EXT_platform_x11
    EGL_EXT_platform_device EGL_KHR_platform_wayland
    EGL_EXT_platform_wayland

Wayland platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
EGL extensions string:
    EGL_EXT_client_sync EGL_EXT_create_context_robustness
    EGL_EXT_output_base EGL_EXT_output_drm
    EGL_EXT_stream_consumer_egloutput EGL_EXT_stream_acquire_mode
    EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs
    EGL_KHR_create_context_no_error EGL_KHR_context_flush_control
    EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_swap_buffers_with_damage
    EGL_KHR_no_config_context EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image EGL_KHR_image_base EGL_KHR_reusable_sync EGL_KHR_stream
    EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture
    EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo
    EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context
    EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_quadruple_buffer
    EGL_NV_stream_cross_display EGL_NV_stream_cross_object
    EGL_NV_stream_cross_process EGL_NV_stream_cross_system
    EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote
    EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet
    EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next
    EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv
    EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time
    EGL_NV_output_drm_flip_event EGL_NV_triple_buffer
    EGL_WL_bind_wayland_display EGL_WL_wayland_eglstream
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8 24  8  0 0 0x00--         y  y  y     win,pb,str
0x02 32  0  8  8  8  8 24  0  0 0 0x00--         y  y  y     win,pb,str
0x03 32  0  8  8  8  8  0  8  0 0 0x00--         y  y  y     win,pb,str
0x04 32  0  8  8  8  8  0  0  0 0 0x00--         y  y  y     win,pb,str
0x05 32  0  8  8  8  8 24  8  2 1 0x00--         y  y  y     win,pb,str
0x06 32  0  8  8  8  8 24  0  2 1 0x00--         y  y  y     win,pb,str
0x07 32  0  8  8  8  8  0  8  2 1 0x00--         y  y  y     win,pb,str
0x08 32  0  8  8  8  8  0  0  2 1 0x00--         y  y  y     win,pb,str
0x09 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     win,pb,str
0x0a 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     win,pb,str
0x0b 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     win,pb,str
0x0c 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     win,pb,str
0x0d 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     win,pb,str
0x0e 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     win,pb,str
0x0f 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     win,pb,str
0x10 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     win,pb,str
0x11 32  0  8  8  8  8 24  8  8 1 0x00--         y  y  y     win,pb,str
0x12 32  0  8  8  8  8 24  0  8 1 0x00--         y  y  y     win,pb,str
0x13 32  0  8  8  8  8  0  8  8 1 0x00--         y  y  y     win,pb,str
0x14 32  0  8  8  8  8  0  0  8 1 0x00--         y  y  y     win,pb,str
0x15 24  0  8  8  8  0 24  8  0 0 0x00--         y  y  y     win,pb,str
0x16 24  0  8  8  8  0 24  0  0 0 0x00--         y  y  y     win,pb,str
0x17 24  0  8  8  8  0  0  8  0 0 0x00--         y  y  y     win,pb,str
0x18 24  0  8  8  8  0  0  0  0 0 0x00--         y  y  y     win,pb,str
0x19 24  0  8  8  8  0 24  8  2 1 0x00--         y  y  y     win,pb,str
0x1a 24  0  8  8  8  0 24  0  2 1 0x00--         y  y  y     win,pb,str
0x1b 24  0  8  8  8  0  0  8  2 1 0x00--         y  y  y     win,pb,str
0x1c 24  0  8  8  8  0  0  0  2 1 0x00--         y  y  y     win,pb,str
0x1d 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     win,pb,str
0x1e 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     win,pb,str
0x1f 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     win,pb,str
0x20 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     win,pb,str
0x21 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     win,pb,str
0x22 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     win,pb,str
0x23 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     win,pb,str
0x24 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     win,pb,str
0x25 24  0  8  8  8  0 24  8  8 1 0x00--         y  y  y     win,pb,str
0x26 24  0  8  8  8  0 24  0  8 1 0x00--         y  y  y     win,pb,str
0x27 24  0  8  8  8  0  0  8  8 1 0x00--         y  y  y     win,pb,str
0x28 24  0  8  8  8  0  0  0  8 1 0x00--         y  y  y     win,pb,str
0x29 16  0  5  6  5  0 24  8  0 0 0x00--         y  y  y     win,pb,str
0x2a 16  0  5  6  5  0 24  0  0 0 0x00--         y  y  y     win,pb,str
0x2b 16  0  5  6  5  0 16  0  0 0 0x00--         y  y  y     win,pb,str
0x2c 16  0  5  6  5  0  0  8  0 0 0x00--         y  y  y     win,pb,str
0x2d 16  0  5  6  5  0  0  0  0 0 0x00--         y  y  y     win,pb,str
0x2e 16  0  5  6  5  0 24  8  2 1 0x00--         y  y  y     win,pb,str
0x2f 16  0  5  6  5  0 24  0  2 1 0x00--         y  y  y     win,pb,str
0x30 16  0  5  6  5  0 16  0  2 1 0x00--         y  y  y     win,pb,str
0x31 16  0  5  6  5  0  0  8  2 1 0x00--         y  y  y     win,pb,str
0x32 16  0  5  6  5  0  0  0  2 1 0x00--         y  y  y     win,pb,str
0x33 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     win,pb,str
0x34 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     win,pb,str
0x35 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     win,pb,str
0x36 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     win,pb,str
0x37 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     win,pb,str
0x38 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     win,pb,str
0x39 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     win,pb,str
0x3a 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     win,pb,str
0x3b 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     win,pb,str
0x3c 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     win,pb,str
0x3d 16  0  5  6  5  0 24  8  8 1 0x00--         y  y  y     win,pb,str
0x3e 16  0  5  6  5  0 24  0  8 1 0x00--         y  y  y     win,pb,str
0x3f 16  0  5  6  5  0 16  0  8 1 0x00--         y  y  y     win,pb,str
0x40 16  0  5  6  5  0  0  8  8 1 0x00--         y  y  y     win,pb,str
0x41 16  0  5  6  5  0  0  0  8 1 0x00--         y  y  y     win,pb,str

X11 platform:
eglinfo: eglInitialize failed

Device platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
EGL extensions string:
    EGL_EXT_client_sync EGL_EXT_create_context_robustness
    EGL_EXT_output_base EGL_EXT_output_drm
    EGL_EXT_stream_consumer_egloutput EGL_EXT_stream_acquire_mode
    EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs
    EGL_KHR_create_context_no_error EGL_KHR_context_flush_control
    EGL_KHR_create_context EGL_KHR_display_reference EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_swap_buffers_with_damage
    EGL_KHR_no_config_context EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image EGL_KHR_image_base EGL_KHR_reusable_sync EGL_KHR_stream
    EGL_KHR_stream_attrib EGL_KHR_stream_consumer_gltexture
    EGL_KHR_stream_cross_process_fd EGL_KHR_stream_fifo
    EGL_KHR_stream_producer_eglsurface EGL_KHR_surfaceless_context
    EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync EGL_NV_quadruple_buffer
    EGL_NV_stream_cross_display EGL_NV_stream_cross_object
    EGL_NV_stream_cross_process EGL_NV_stream_cross_system
    EGL_NV_stream_flush EGL_NV_stream_metadata EGL_NV_stream_remote
    EGL_NV_stream_reset EGL_NV_stream_socket EGL_NV_stream_socket_inet
    EGL_NV_stream_socket_unix EGL_NV_stream_sync EGL_NV_stream_fifo_next
    EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv
    EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time
    EGL_NV_output_drm_flip_event EGL_NV_triple_buffer
    EGL_WL_bind_wayland_display EGL_WL_wayland_eglstream
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8 24  8  0 0 0x00--         y  y  y     pb,str
0x02 32  0  8  8  8  8 24  0  0 0 0x00--         y  y  y     pb,str
0x03 32  0  8  8  8  8  0  8  0 0 0x00--         y  y  y     pb,str
0x04 32  0  8  8  8  8  0  0  0 0 0x00--         y  y  y     pb,str
0x05 32  0  8  8  8  8 24  8  2 1 0x00--         y  y  y     pb,str
0x06 32  0  8  8  8  8 24  0  2 1 0x00--         y  y  y     pb,str
0x07 32  0  8  8  8  8  0  8  2 1 0x00--         y  y  y     pb,str
0x08 32  0  8  8  8  8  0  0  2 1 0x00--         y  y  y     pb,str
0x09 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     pb,str
0x0a 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     pb,str
0x0b 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     pb,str
0x0c 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     pb,str
0x0d 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     pb,str
0x0e 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     pb,str
0x0f 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     pb,str
0x10 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     pb,str
0x11 32  0  8  8  8  8 24  8  8 1 0x00--         y  y  y     pb,str
0x12 32  0  8  8  8  8 24  0  8 1 0x00--         y  y  y     pb,str
0x13 32  0  8  8  8  8  0  8  8 1 0x00--         y  y  y     pb,str
0x14 32  0  8  8  8  8  0  0  8 1 0x00--         y  y  y     pb,str
0x15 24  0  8  8  8  0 24  8  0 0 0x00--         y  y  y     pb,str
0x16 24  0  8  8  8  0 24  0  0 0 0x00--         y  y  y     pb,str
0x17 24  0  8  8  8  0  0  8  0 0 0x00--         y  y  y     pb,str
0x18 24  0  8  8  8  0  0  0  0 0 0x00--         y  y  y     pb,str
0x19 24  0  8  8  8  0 24  8  2 1 0x00--         y  y  y     pb,str
0x1a 24  0  8  8  8  0 24  0  2 1 0x00--         y  y  y     pb,str
0x1b 24  0  8  8  8  0  0  8  2 1 0x00--         y  y  y     pb,str
0x1c 24  0  8  8  8  0  0  0  2 1 0x00--         y  y  y     pb,str
0x1d 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     pb,str
0x1e 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     pb,str
0x1f 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     pb,str
0x20 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     pb,str
0x21 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     pb,str
0x22 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     pb,str
0x23 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     pb,str
0x24 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     pb,str
0x25 24  0  8  8  8  0 24  8  8 1 0x00--         y  y  y     pb,str
0x26 24  0  8  8  8  0 24  0  8 1 0x00--         y  y  y     pb,str
0x27 24  0  8  8  8  0  0  8  8 1 0x00--         y  y  y     pb,str
0x28 24  0  8  8  8  0  0  0  8 1 0x00--         y  y  y     pb,str
0x29 16  0  5  6  5  0 24  8  0 0 0x00--         y  y  y     pb,str
0x2a 16  0  5  6  5  0 24  0  0 0 0x00--         y  y  y     pb,str
0x2b 16  0  5  6  5  0 16  0  0 0 0x00--         y  y  y     pb,str
0x2c 16  0  5  6  5  0  0  8  0 0 0x00--         y  y  y     pb,str
0x2d 16  0  5  6  5  0  0  0  0 0 0x00--         y  y  y     pb,str
0x2e 16  0  5  6  5  0 24  8  2 1 0x00--         y  y  y     pb,str
0x2f 16  0  5  6  5  0 24  0  2 1 0x00--         y  y  y     pb,str
0x30 16  0  5  6  5  0 16  0  2 1 0x00--         y  y  y     pb,str
0x31 16  0  5  6  5  0  0  8  2 1 0x00--         y  y  y     pb,str
0x32 16  0  5  6  5  0  0  0  2 1 0x00--         y  y  y     pb,str
0x33 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     pb,str
0x34 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     pb,str
0x35 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     pb,str
0x36 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     pb,str
0x37 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     pb,str
0x38 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     pb,str
0x39 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     pb,str
0x3a 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     pb,str
0x3b 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     pb,str
0x3c 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     pb,str
0x3d 16  0  5  6  5  0 24  8  8 1 0x00--         y  y  y     pb,str
0x3e 16  0  5  6  5  0 24  0  8 1 0x00--         y  y  y     pb,str
0x3f 16  0  5  6  5  0 16  0  8 1 0x00--         y  y  y     pb,str
0x40 16  0  5  6  5  0  0  8  8 1 0x00--         y  y  y     pb,str
0x41 16  0  5  6  5  0  0  0  8 1 0x00--         y  y  y     pb,str
```

</details>

I don't have the `glinfo` command (I can't seem to find any package providing it either) so I can't test that.

**Comment by ZeGentzy** [comment] 2019-07-14 22:16
Do you still experience this issue with nouveau?

**Comment by aidanharris** [comment] 2019-07-14 22:44
A reboot later and it seems to work fine with Nouveau. The examples run and I know I'm using Nouveau (other than `lsmod` telling me so) because I managed to cause the Linux kernel to hang which is sadly typical behaviour for Nouveau :(

**Comment by ZeGentzy** [comment] 2019-07-14 23:07
That's unfortunate. I was hoping this issue would also take place on Nouveau, so that we could rebuild mesa with debug symbols and look into why it was failing.

Since the NVIDIA binary driver does not release it's source, you can't compile it with debug symbols.

Can you use apitrace to trace all the EGL calls w/ the proprietary driver?

**Comment by ZeGentzy** [comment] 2019-07-14 23:21
Other question: do other programs that use EGL also fail, or is this a glutin only thing?

**Comment by aidanharris** [comment] 2019-07-14 23:35
I can run `weston-simple-egl` and `eglgears_wayland` (from [mesa-demos](https://gitlab.freedesktop.org/mesa/demos)).

I've installed apitrace but I'm not sure what I need to do to capture a trace. Running `apitrace trace --api egl ./target/debug/examples/window` produced a .trace file.

**Comment by ZeGentzy** [comment] 2019-07-14 23:54
The trace file should not be empty. Just upload it when you make one successfully. Make sure the glutin examples are not panicing.

**Comment by bertin0** [comment] 2021-02-11 20:37
Here is my EGL trace of running the window example.

https://www.mediafire.com/file/vf8pecdropycjrw/window.trace/file

**Comment by dbrgn** [comment] 2021-05-02 12:10
Same issue here, it prevents alacritty from working under Wayland.

System: GTX 760, nvidia 465.27, wlroots-eglstreams + sway.

I ran `apitrace trace --api=egl -o window.egl.trace target/debug/examples/window`, here's the gzipped output:

[window.egl.trace.gz](https://github.com/rust-windowing/glutin/files/6411295/window.egl.trace.gz)

Does that help? Is there anything else I can provide?

**Comment by dbrgn** [comment] 2021-05-02 13:43
Comment in https://github.com/danvd/wlroots-eglstreams/issues/15:

> Yes, It's a bug of nvidia blob. There are probably some constraints on egl context.

**Comment by danvd** [comment] 2021-05-11 04:26
Remark. eglGetError(), if called just before the subject error is raised, returns the following:
```
EGL_BAD_NATIVE_WINDOW 0x300B
An EGLNativeWindowType argument does not refer to a valid
native window.
```
native window is usually created with call to `wl_compositor_create_surface` followed by `wl_egl_window_create`.
And looks like the latter returns invalid handle (or maybe this handle becomes invalid when `eglCreateWindowSurface` is executed)

**Comment by flindeberg** [comment] 2021-07-01 12:21
Same issue here.

(My guess is that more and more peeps will have this issue now that the Nvidia-driver supports hardware accelerated `xwayland` and more people make the switch to Wayland.)

**Comment by VitalyAnkh** [comment] 2021-07-21 16:18
@flindeberg 
> (My guess is that more and more peeps will have this issue now that the Nvidia-driver supports hardware accelerated xwayland and more people make the switch to Wayland.)

Yeah the support for Wayland and hardware accleration for Xwayland of  Nvidia 470 driver seduced me into switching from nouveau to the proprietary driver. But this issue is really a big problem for me. All apps based on `winit` can't launch, and we can't build Wayland apps with game engines or GUI libraries which use `winit`.

I wonder if Nvidia proprietary driver never supports `glutin` for this issue opened in 2019 is still open today? If so, it's too bad.

**Comment by danvd** [comment] 2021-07-24 17:08
All major UI libraries do support 470 driver. Among them: GTK3, SDL2, GLFW, KDE. The issue with winit became more important after termite was obsoleted by alacritty.

**Comment by VitalyAnkh** [comment] 2021-07-25 03:21
@danvd 
> All major UI libraries do support 470 driver. Among them: GTK3, SDL2, GLFW, KDE. The issue with winit became more important after termite was obsoleted by alacritty.

In fact winit do support nvidia 470 driver as long as we add a environment variable: `WINIT_UNIX_BACKEND=x11`, then apps based on `winit` could run under x11 with nvidia 470 driver. This is a workaround you could try if you just want your apps run with 470 driver. Thus the problem is `winit`'s Wayland backend does not support nvidia 470 driver.

**Comment by danvd** [comment] 2021-07-25 03:46
Yes, I meant Wayland support of course. X11 backend works just fine.

**Comment by tchebb** [comment] 2021-08-15 07:55
This seems likely to be caused by NVIDIA/egl-wayland#34.

**Comment by VitalyAnkh** [comment] 2021-08-31 01:53
This is fixed by https://github.com/NVIDIA/egl-wayland/commit/2eb4628d64a8297fb4c08aa796fdf33ff54a670f. I tested many examples and they worked well!

**Closed** 2022-09-03 06:39 UTC
Labels: type: bug, platform: Wayland, difficulty: hard, status: waiting, priority: low
