### ISSUE TITLE
glutin-0.26.0 issue with fn finish - mismatch type

### ISSUE THREAD

**Issue by ImreMD** [rust-windowing/glutin#1455] opened 2022-09-03 17:29 UTC
Hello, I have a problem with glutin-0.26.0 (it's one of the dependencies of rltk crate) here the output from the build process:

.and_then(|p| p.finish(hwnd)) 
                   ------ ^^^^ expected `isize`, found *-ptr
                  arguments to this function are incorrect

I am on Window 10. What can be done? Should I downgrade (patch) the crate?

**Comment by Jerrody** [comment] 2022-09-03 17:30
That was mentioned in issue: 
https://github.com/rust-windowing/glutin/issues/1454

**Comment by kchibisov** [comment] 2022-09-03 18:22
Duplicate of #1454 .

**Closed by kchibisov** 2022-09-03 18:22 UTC
