### ISSUE TITLE
WASM/WebGL support with `glow`?

### ISSUE THREAD

**Issue by elimerl** [rust-windowing/glutin#1466] opened 2022-09-10 04:24 UTC
Hi,

I'd like to write an OpenGL (using glow) app that can run on both web and desktop with minimal code changes. Is there support for this, or do I have to use `cfg(target_arch)`? If not glutin, is there another crate that provides this functionality? Thanks.

**Comment by kchibisov** [comment] 2022-09-10 06:10
duplicate of  #1167.  

There's interest in supporting wasm in glutin, but right now there's no webgl support.

**Closed by kchibisov** 2022-09-10 06:10 UTC
