### ISSUE TITLE
closing window with vsync does not kill process

### ISSUE THREAD

**Issue by Veemon** [rust-windowing/glutin#862] opened 2017-02-25 04:11 UTC
Creating a window via:
```rust
let builder = glutin::WindowBuilder::new()
  .with_dimensions(1280, 720)
  .with_title("some stuff i can't paste")
  .with_vsync();
```

and capturing it's close event:
```rust
glutin::Event::Closed => return;
```

does not return the function.

**Comment by francesca64** [comment] 2018-05-30 21:36
Which platform?

**Comment by dannyfritz** [comment] 2018-05-30 21:37
Windows 10

**Comment by francesca64** [comment] 2018-06-02 17:19
I've succeeded in reproducing this. Do you also encounter this problem with the glutin example programs?

**Comment by francesca64** [comment] 2018-06-02 18:16
Okay, so it actually does close. It just takes over a minute (and potentially several). It seems that receiving events is badly delayed (not just `CloseRequested`, since it also happens when closing the window with escape). It's still unacceptably delayed with vsync disabled (IMO), but it's easily 10x faster.

Try swapping out the `run_forever` in the triangle example with this:
```rust
let mut running = true;
while running {
    events_loop.poll_events(|event| {
        use glutin::{ControlFlow, Event, KeyboardInput, VirtualKeyCode, WindowEvent};

        if let Event::WindowEvent { event, .. } = event {
            match event {
                WindowEvent::CloseRequested |
                WindowEvent::KeyboardInput {
                    input: KeyboardInput {
                        virtual_keycode: Some(VirtualKeyCode::Escape),
                        ..
                    },
                    ..
                } => running = false,
                WindowEvent::Resized(width, height) => {
                    window.resize(width, height);
                    gfx_window_glutin::update_views(&window, &mut data.out, &mut main_depth);
                },
                _ => (),
            }
        }
    });

    // draw a frame
    encoder.clear(&data.out, CLEAR_COLOR);
    encoder.draw(&slice, &pso, &data);
    encoder.flush(&mut device);
    window.swap_buffers().unwrap();
    device.cleanup();
}
```

For me, it works perfectly. This is also likely why I've never encountered this issue before.

Using vsync with `run_forever` (while rendering from the same thread as processing events) means that you block on vblank after every single event. For that reason, the length of time it takes before the window finally closes is directly proportional to the number of queued events (note that every mouse motion generates *multiple* events). You can confirm this by running the example, not moving the mouse or doing anything else, and then closing the window using escape; it happens instantly. Using `poll_events`, it only blocks after each time the event queue is emptied, which greatly cuts down on latency.

As for why `run_forever` is slow even without vsync, well, you're still rendering after every single event, so you'll still be behind on the event queue.

If you really want to use `run_forever`, then I suggest rendering on another thread. Though, if you do that, due to a bug in the X11 backend every Xlib call you make (i.e. through `get_inner_size`, etc.) will block until the next event processed, so your application will be broken on Linux. Improving winit's event loop is actually one of my highest priorities, it's just that these things take time... tomaka/winit#459

**Comment by dannyfritz** [comment] 2018-06-04 23:11
`poll_events` and `loop {}` is definitely the way to go. 👍

**Comment by promethe42** [comment] 2018-07-02 06:17
The window will *not* close on Ubuntu 16.04.

It still does *not* work after I modified the `triangle.rs` example to use the fix proposed by @francesca64 :

```rust
let mut running = true;
    while running {
        events_loop.poll_events(|event| {
            use glutin::{Event, WindowEvent, KeyboardInput, VirtualKeyCode};

            if let Event::WindowEvent { event, .. } = event {
                match event {
                    WindowEvent::CloseRequested |
                    WindowEvent::KeyboardInput {
                        input: KeyboardInput {
                            virtual_keycode: Some(VirtualKeyCode::Escape),
                            ..
                        },
                        ..
                    } => running = false,
                    WindowEvent::Resized(width, height) => {
                        window.resize(width, height);
                    },
                    _ => (),
                }
            }

            unsafe {
                // Clear the screen to black
                gl::ClearColor(0.3, 0.3, 0.3, 1.0);
                gl::Clear(gl::COLOR_BUFFER_BIT);

                // Draw a triangle from the 3 vertices
                gl::DrawArrays(gl::TRIANGLES, 0, 3);
            }

            gl_window.swap_buffers().unwrap();
        });
    }
```

AFAIK vsync is not even enable.

**Comment by francesca64** [comment] 2018-07-02 12:37
It looks like you're rendering in the `poll_events` callback, which isn't really an improvement over doing it in the `run_forever` callback.

**Comment by promethe42** [comment] 2018-07-02 12:51
> It looks like you're rendering in the poll_events callback, which isn't really an improvement over doing it in the run_forever callback.

You're absolutely right.

The following code has the expected behavior (windows closes when clicking the cross or when pressing the escape key):

```rust
let mut running = true;
    while running {
        events_loop.poll_events(|event| {
            use glutin::{Event, WindowEvent, KeyboardInput, VirtualKeyCode};

            if let Event::WindowEvent { event, .. } = event {
                match event {
                    WindowEvent::CloseRequested |
                    WindowEvent::KeyboardInput {
                        input: KeyboardInput {
                            virtual_keycode: Some(VirtualKeyCode::Escape),
                            ..
                        },
                        ..
                    } => running = false,
                    _ => (),
                }
            }
        });

        unsafe {
            // Clear the screen to black
            gl::ClearColor(0.3, 0.3, 0.3, 1.0);
            gl::Clear(gl::COLOR_BUFFER_BIT);

            // Draw a triangle from the 3 vertices
            gl::DrawArrays(gl::TRIANGLES, 0, 3);
        }

        gl_window.swap_buffers().unwrap();
    }
```

Thank you!

**Comment by ZeGentzy** [comment] 2019-05-20 07:45
We got eventsloop v2 now. Closing because this is outdated.

**Closed by ZeGentzy** 2019-05-20 07:45 UTC
Labels: platform: Windows, status: upstream, type: bug
