### ISSUE TITLE
Context creation sometimes fails on windows

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#515] opened 2015-07-04 11:16 UTC
That's on my machine!
AMD video card.

The error happens because `wglCreateContextAttribsARB()` returns null.
The error code returned by `GetLastError()` is usually 0 (indicating a success), but I have just got a 2004 error code instead, which is `ERROR_TRANSFORM_NOT_SUPPORTED`. I think that these problems are the same.

According to google results this is a thread-safety related problem, but that seems weird.

**Comment by yg-yu** [comment] 2015-10-13 07:25
My Pc, Intel video card support latest version OpenGL is v3.1
if use glutin create Window not set opengl version or set opengl version > v3.1:
```thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: "wglCreateContextAttribsARB failed: OS Error -1073274731 (FormatMessageW() returned error 317) (os error -1073274731)"', ../src/libcore\result.rs:732```
set opengl version <= 3.1, work well.
There as some test code
```
use opengl_graphics::OpenGL;
use glutin_window::GlutinWindow as Window;
use piston::window::WindowSettings;

// const OPEN_GL: OpenGL = OpenGL::V3_1;

fn main() {
   
    let window = Window::new(
        WindowSettings::new("test",
                            [BOARD_WIDTH as u32 * TILE_SIZE as u32, BOARD_HEIGHT as u32 * TILE_SIZE as u32])
            .exit_on_esc(true)
            // .opengl(OPEN_GL)
	    ).unwrap();

}
```

**Comment by tomaka** [comment] 2015-10-13 08:29
@yg-yu Does your problem happen all the time?

**Comment by tomaka** [comment] 2015-10-13 08:31
For some background, I have thought a bit about this a few weeks ago. My only hypothesis is that this is due to `WM_CREATE` not being received yet when the context is created.

**Comment by yg-yu** [comment] 2015-10-13 11:59
@tomaka  Cause panicked everytime，not randomly.  and  sorry， the crate I used to create window have problem is piston's glutin_window not glutin.   direct use glutin to create window wouldn't  cause panick ( [glutin window example](https://github.com/tomaka/glutin/blob/master/examples/window.rs) run well).

**Comment by tomaka** [comment] 2015-10-16 08:24
> More generally, I have thought a bit about this a few weeks ago. My only hypothesis is that this is due to WM_CREATE not being received yet when the context is created. But this is based on nothing, just a supposition.

I looked into this. In fact `WM_CREATE` is sent before `CreateWindow` returns, so this is not the issue.

**Comment by application-developer-DA** [comment] 2017-05-15 09:33
I have the same error mesage as @sickHamm, it crashes when I try to use `piston_window` to create a window (I believe `piston_window` relies on `glutin` as a default backend). I've seen several issues which may have been caused by the same issue (I'm not 100% sure about that, but the error message is exactly the same): https://github.com/PistonDevelopers/piston_window/issues/143, https://github.com/PistonDevelopers/piston_window/issues/163.

**Comment by zpgaal** [comment] 2017-08-16 20:53
I've just experienced the same thing during exit.
Since we have the close event handling where window shall be still active to release the gl context.
Once a while if the window is closed by the X button calling make_current sometimes failes with the given error message.

(thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Error { repr: Os { code: -1073283066, message: "OS Error -1073283066 (FormatMessageW() returned error 317)" } })', src\libcore\result.rs:859
stack backtrace:)

Just guessing that the close message arrives too late. it might be some thread related, message passing issue.

**Comment by kchibisov** [comment] 2022-09-03 06:46
Closing due to inactivity.

**Closed by kchibisov** 2022-09-03 06:46 UTC
Labels: type: bug, platform: Windows, difficulty: hard
