### ISSUE TITLE
Create Context from RawWindowHandle?

### ISSUE THREAD

**Issue by nifker** [rust-windowing/glutin#1305] opened 2020-06-06 13:17 UTC
I think it might be useful if glutin would support creating a RawContext from a handle: https://docs.rs/raw-window-handle/0.3.3/raw_window_handle/enum.RawWindowHandle.html
I would create a PR for that, if there's interest.

**Comment by kchibisov** [comment] 2020-06-09 21:56
Seems like a duplicate of https://github.com/rust-windowing/glutin/issues/1271 ?

**Closed by kchibisov** 2020-06-09 21:56 UTC
