### ISSUE TITLE
Errors compiling for Android

### ISSUE THREAD

**Issue by lattice0** [rust-windowing/glutin#1405] opened 2022-05-19 02:07 UTC
I'm trying to compile for android x86_64, I added no additional features, and compiling for linux x86_64 works. I'm getting:

```
error[E0599]: no method named `set_suspend_callback` found for reference `&EventLoopWindowTarget<T>` in the current scope
  --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/api/android/mod.rs:76:12
   |
76 |         el.set_suspend_callback(Some(Box::new(move |suspended| {
   |            ^^^^^^^^^^^^^^^^^^^^ method not found in `&EventLoopWindowTarget<T>`

error[E0615]: attempted to take value of method `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/api/egl/mod.rs:621:17
    |
621 |         if !egl.SwapBuffersWithDamageKHR.is_loaded() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
621 |         if !egl.SwapBuffersWithDamageKHR(_, _, _, _).is_loaded() {
    |                                         ++++++++++++

error[E0615]: attempted to take value of method `SwapBuffersWithDamageKHR` on type `&api::egl::egl::Egl`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.27.0/src/api/egl/mod.rs:664:13
    |
664 |         egl.SwapBuffersWithDamageKHR.is_loaded()
    |             ^^^^^^^^^^^^^^^^^^^^^^^^ method, not a field
    |
help: use parentheses to call the method
    |
664 |         egl.SwapBuffersWithDamageKHR(_, _, _, _).is_loaded()
    |                                     ++++++++++++

Some errors have detailed explanations: E0599, E0615.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `glutin` due to 3 previous errors
```

What is happening?

**Comment by MarijnS95** [comment] 2022-05-26 13:58
Going to close this as a duplicate of #1307, so that we only have one tracking issue!

**Closed by MarijnS95** 2022-05-26 13:58 UTC
Labels: status: duplicate, platform: Android
