### ISSUE TITLE
Assertion `!xcb_xlib_threads_sequence_lost' failed

### ISSUE THREAD

**Issue by kuviman** [rust-windowing/glutin#1034] opened 2018-06-24 12:12 UTC
Trying to run on Ubuntu 14.04

```
kuviman@UbuntuBox:~/Temp/glutin$ cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/examples/window`
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
window: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped)
```

**Comment by kuviman** [comment] 2018-06-24 12:43
According to `Cargo.lock`, I'm on `winit` 0.15.1, still have the issue.

I'll take a look at the linked issue, maybe it should be reopened.

**Comment by kuviman** [comment] 2018-06-24 13:18
Running [multithread_window](https://github.com/azriel91/multithread_window) with winit 0.15.1 is ok, can't reproduce the issue with that.

Running glutin's `--example window` reproduces this reliably though.

Also, it runs fine on my Arch Linux laptop, but reproduces every time with both Ubuntu 14.04 and 18.04 in VirtualBox, if that helps.

**Comment by kuviman** [comment] 2018-06-24 16:13
Some more details: my VM was set to use only 1 CPU, when I changed it to more than that, it runs successfully like 70% of times.

**Comment by azriel91** [comment] 2018-07-01 03:17
Hiya, I accidentally created a way to reproduce this issue. I've put it on the `glutin-xlib-sequence-lost` branch of [multithread_window](https://github.com/azriel91/multithread_window). Cut and paste commands:

```bash
git clone -b glutin-xlib-sequence-lost --depth 1 git@github.com:azriel91/multithread_window.git
cd multithread_window
cargo run # to compile it

# Limited it to 5 because it can be hard to stop when the windows keep popping up.
for i in {1..5}; do target/debug/multithread_window; done
```

The sample output:

```
$ for i in {1..5}; do target/debug/multithread_window; done
Spawned threads.
Xlib: sequence lost (0x1015e > 0x162) in reply type 0x0!
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
multithread_window: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Spawned threads.
Waited for 400 ms.
Spawned threads.
Waited for 400 ms.
Spawned threads.
Spawned threads.
Xlib: sequence lost (0x1015f > 0x163) in reply type 0x0!
Xlib: sequence lost (0x10173 > 0x177) in reply type 0x0!
Xlib: sequence lost (0x10171 > 0x177) in reply type 0x0!
Xlib: sequence lost (0x10183 > 0x187) in reply type 0x0!
```

The ``Assertion `!xcb_xlib_threads_sequence_lost'`` assertion message doesn't seem to happen very often compared to the `Xlib: sequence lost` message. I've run the loop under `xvfb-run` and so far haven't seen the `Assertion` message.

[This linuxquestions](https://www.linuxquestions.org/questions/programming-9/%5Bxlib-motif%5D-xlib-sequence-lost-in-reply-type-4175490549/) thread looks useful.

**Comment by ZeGentzy** [comment] 2019-03-22 05:39
To my horror I can still reproduce this with 0.20. Nooooo!
```
A
Xlib: sequence lost (0x100cb > 0xce) in reply type 0x0!
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
multithread_window: xcb_io.c:263: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
A
Xlib: sequence lost (0x10201 > 0x204) in reply type 0x0!
B
A
Xlib: sequence lost (0x10121 > 0x133) in reply type 0x0!
Xlib: sequence lost (0x10407 > 0x40a) in reply type 0x0!
B
A
B
A
Xlib: sequence lost (0x100ec > 0xed) in reply type 0x0!
Xlib: sequence lost (0x101d7 > 0x1e2) in reply type 0x0!
B
```

```
diff --git a/src/main.rs b/src/main.rs
index be97219..b510746 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -3,33 +3,29 @@ extern crate glutin;
 use std::thread::{self, JoinHandle};
 use std::time::Duration;
 
-use glutin::{GlContext, GlProfile, GlRequest};
+use glutin::{ContextTrait, GlProfile, GlRequest};
 
-const THREAD_COUNT: usize = 10;
+const THREAD_COUNT: usize = 32;
 
 fn open_window() {
-    let mut events_loop = glutin::EventsLoop::new();
+    let mut el = glutin::EventsLoop::new();
 
-    let context = glutin::ContextBuilder::new()
+    let wb = glutin::WindowBuilder::new()
+        ;//.with_visibility(false);
+
+    let gl_window = glutin::ContextBuilder::new()
         .with_multisampling(0)
         .with_vsync(false)
         .with_gl_profile(GlProfile::Core)
-        .with_gl(GlRequest::Latest);
-
-    let window = glutin::WindowBuilder::new();
-    let gl_window = glutin::GlWindow::new(window, context, &events_loop).unwrap();
+        .with_gl(GlRequest::Latest)
+        .build_windowed(wb, &el)
+        .unwrap();
 
     let _ = unsafe { gl_window.make_current() };
 
-    // println!(
-    //     "Pixel format of the window's GL context: {:?}",
-    //     gl_window.get_pixel_format()
-    // );
-
     let mut running = true;
     while running {
-        events_loop.poll_events(|event| {
-            // println!("{:?}", event);
+        el.poll_events(|event| {
             if let glutin::Event::WindowEvent { event, .. } = event {
                 match event {
                     glutin::WindowEvent::CloseRequested => running = false,
@@ -65,8 +61,7 @@ fn main() {
     }
 
     thread::spawn(move || wait_for_threads(thread_handles));
-    println!("Spawned threads.");
-
-    thread::sleep(Duration::from_millis(400));
-    println!("Waited for 400 ms.");
+    println!("A");
+    thread::sleep(Duration::from_millis(1000));
+    println!("B");
 }
```

**Comment by ZeGentzy** [comment] 2019-03-22 05:41
If I turn on `.with_visibility(false);` I can get either a SEGV or a ABORT sometimes, but not the sequence lost errors. I can not reproduce this when using valgrind or GDB. This is going to be a PITA, but hopefully I catch it.

**Comment by ZeGentzy** [comment] 2019-03-23 18:03
According to the folks at #xorg-devel (Thanks DrNick), we've rediscovered https://bugs.freedesktop.org/show_bug.cgi?id=99781

**Comment by ZeGentzy** [comment] 2019-03-24 21:30
Hey, 

For those willing to compile their own copy of mesa to test this out, try taking this patch for a spin: https://bugs.freedesktop.org/attachment.cgi?id=143767

**Comment by ZeGentzy** [comment] 2019-03-26 20:15
https://gitlab.freedesktop.org/mesa/mesa/merge_requests/523

**Comment by ZeGentzy** [comment] 2019-04-30 04:48
Patch has been merged. Next version of mesa will fix this!

**Comment by ZeGentzy** [comment] 2019-06-21 21:08
This is unfortunate, but our patch got reverted due to breaking wine applications:
https://bugs.freedesktop.org/show_bug.cgi?id=110632

**Comment by Rami-Slicer** [comment] 2021-10-05 16:41
I'm getting this issue too with the examples; it crashes 50% of the time. Are there any workarounds I can use?

**Comment by markus-bauer** [comment] 2022-01-08 11:12
I'm encountering this issue too.
I'm using the newest Xubuntu (21.10) with X11 and Mesa (21.2.2), but use i3 as a window manager. 

As a test, I ran the basic window example (https://github.com/rust-windowing/glutin/blob/master/glutin_examples/examples/window.rs), using glutin 0.28.0, in a loop n times.

- It (almost) always fails under i3. Success: 5/100.
- I also tried i3 with a compositor (compton and picom with default settings), but didn't notice any improvements.
- It always works under xfce. Success: 30/30.
 
Note that the crash never happens on another machine that also runs i3 but uses NVIDIA drivers.

So at least for me, this bug is also related to the desktop environment / window manager. I think future reports should include this info.

**Comment by NiceneNerd** [comment] 2022-03-18 02:06
I can confirm the same issue on Arch under both i3 and Plasma, though the success rate is slightly higher on Plasma.

**Comment by markus-bauer** [comment] 2022-05-16 08:46
I totally forgot about this.

It looks like this issue is fixed for me after I upgraded to the latest ubuntu (22.04).
It has Mesa 22.0.1.

**Comment by thepperson** [comment] 2022-05-16 14:42
I also had it resolved by upgrading to ubuntu 22.04 from 21.04. Hardware is a virtualbox machine.

**Comment by teteenpapier** [comment] 2022-05-27 14:50
Got this issue too. I tried on Ubuntu 20 (VM and real hardware) with Gnome. I've tried others distributions and DE/WM and they work fine : 
* Ubuntu 20 - XFCE
* Ubuntu 22 - Gnome
* Arch- i3 Ubuntu 22

**Comment by cbrown1234** [comment] 2022-06-18 11:12
I've also experienced this issue:
```
❯ cargo run -p hello_world
     Finished dev [unoptimized + debuginfo] target(s) in 0.09s
      Running `target/debug/hello_world`
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
hello_world: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed. 
fish: Job 1, 'cargo run -p hello_world' terminated by signal SIGABRT (Abort)
```

Env:
https://github.com/emilk/egui/ - master @ 7eeb292adfacd9311a420ac3ea225e2261a8f8d3
Ubuntu 20.04 on Virtualbox
and I had installed the prerequisites 
```
sudo apt-get install -y libclang-dev libgtk-3-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
```

**Comment by lattice0** [comment] 2022-06-19 01:43
Same here. Ubuntu 22.04

**Comment by kchibisov** [comment] 2022-09-03 06:38
I think it was an issue with mesa that got fixed. Anyway glutin doesn't depend on winit anymore..

**Closed by kchibisov** 2022-09-03 06:38 UTC
Labels: type: bug, platform: X11, status: waiting, status: upstream
